created homescreen
AceLeft/Interfact-Admin-Dashboard pull request #16
Opened 2024-11-30 16:51 UTC by Ethan-Chester

2024-11-30 19:25 UTC, AceLeft approved these changes

2024-11-30 20:20 UTC, AceLeft requested changes
I'm not super sure about using AI art

2024-11-30 21:53 UTC, SaltyTea4924 approved these changes

2024-12-01 00:53 UTC, AceLeft approved these changes
I replaced the AI generated art with a public domain photo. Sorry if it feels like I'm being stubborn about this, I just have to stick with my beliefs

2024-12-01 01:04 UTC, merged